# Generated by Django 3.1.7 on 2021-04-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idusuario',
            new_name='idusuario',
        ),
    ]
