# Generated by Django 3.1.7 on 2021-04-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('medida', models.CharField(max_length=50)),
            ],
        ),
    ]
