# Generated by Django 3.1.7 on 2021-04-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('modopreparo', models.TextField(max_length=1000)),
            ],
        ),
    ]
