# Generated by Django 3.1.7 on 2021-04-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='modopreparo',
            new_name='modopreparo',
        ),
    ]
