# Generated by Django 3.1.7 on 2021-04-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
        ('receitas', '0002_auto_20210407_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utiliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=7)),
                ('nomealimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento')),
                ('nomereceita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receita')),
            ],
            options={
                'unique_together': {('nomereceita', 'nomealimento')},
            },
        ),
    ]
