# Generated by Django 3.1.7 on 2021-04-10 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('receitas', '0003_utiliza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondencia', models.DecimalField(decimal_places=3, max_digits=7)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('nomereceita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receita')),
            ],
            options={
                'unique_together': {('nomereceita', 'idusuario')},
            },
        ),
    ]
