# Generated by Django 3.1.7 on 2021-04-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datavalidade', models.DateField(null=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=7)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('nomealimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento')),
            ],
            options={
                'unique_together': {('idusuario', 'nomealimento', 'datavalidade')},
            },
        ),
    ]
