# Generated by Django 3.1.7 on 2021-04-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210412_1204'),
        ('alimentos', '0001_initial'),
        ('possui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='possui',
            old_name='datavalidade',
            new_name='datavalidade',
        ),
        migrations.RenameField(
            model_name='possui',
            old_name='idusuario',
            new_name='idusuario',
        ),
        migrations.RenameField(
            model_name='possui',
            old_name='nomealimento',
            new_name='nomealimento',
        ),
        migrations.AlterUniqueTogether(
            name='possui',
            unique_together={('idusuario', 'nomealimento', 'datavalidade')},
        ),
    ]
